language: python
python:
  - "3.8"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential python-dev graphviz libgraphviz-dev
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov=./
# code coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 715c74eb-d4fd-4f50-8d38-930ea5ebe9a2