language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential python-dev graphviz libgraphviz-dev
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest